<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categories</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/global.css">
</head>
<body class="bg-gray-100">
    <nav id="nav" class="flex sticky z-50 top-0 w-full h-18 py-1 justify-between items-center shadow-0 px-20 shadow-slate-300 bg-[--bg]"></nav>
    
    <section id="categoryContainer" class="flex max-w-5xl mx-auto overflow-x-auto space-x-2 py-4 px-2 scrollbar-thin scrollbar-thumb-gray-400">
        <!-- Category buttons generated by servlet -->
        ${categoryButtons}
    </section>
    
    <div class="max-w-5xl mx-auto flex justify-between items-center mt-5 mb-2">
        <p class="text-3xl font-semibold text-[--secondary]">Explore</p>
        <a href="/LBMS/category" class="font-semibold h-10 text-xl text-center text-[--secondary] hover:underline">All Category >></a>
    </div>
    
    <section id="explore" class="max-w-5xl flex flex-wrap justify-between mx-auto h-full mb-5 gap-5">
        <!-- Book cards generated by servlet -->
        ${bookCards}
    </section>

    <div class="max-w-5xl mx-auto flex justify-center items-center space-x-2 py-4">
        <!-- Pagination controls generated by servlet -->
        ${paginationControls}
    </div>

      <footer
        id="footer"
        role="contentinfo"
        class="pb-20 pt-10 mt-10 border-t-2 border-[--secondary]"
      >

      </footer>
          <script src="./scripts/innerHtmlInserter.js"></script>

</body>
</html>
