<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categories</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <div id="categoryContainer" class="flex overflow-x-auto space-x-2 py-4 px-2 scrollbar-thin scrollbar-thumb-gray-400">
        <!-- Category buttons generated by servlet -->
        ${categoryButtons}
    </div>

    <script>
    function filterByCategory(category) {
        console.log('Filter by category:', category);
        const encodedCategory = encodeURIComponent(category);
        console.log('Encoded Category:', encodedCategory);
        let newUrl = 'filter?category=' + encodedCategory;
        console.log('newUrl:', newUrl);
        
        window.location.href = newUrl;
    }

    const categoryButtons = document.querySelectorAll(".category-btn");

    categoryButtons.forEach(button => {
        button.addEventListener("click", function(event) {
            event.preventDefault();
            event.stopPropagation();
            
            const category = button.getAttribute('data-category');
            console.log('Button clicked with category:', category);
            
            filterByCategory(category);
        });
    });
    </script>
</body>
</html>
